theme = "beautifulhugo"
baseURL = "https://blog.rmhogervorst.nl/"
languageCode = "en-us"
title = "Roel's R-tefacts"
pygmentsCodeFences = true
pygmentsUseClasses = false
pygmentsStyle = "trac"
pygmentsUseClassic = true
enableEmoji = true
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
publishDir = "public"
  
[permalinks]
    post = "/blog/:year/:month/:day/:slug/"
    
[Params]
  subtitle = "Tips about clean R-code and reproducible work, but also fun!"
  logo = "img/avatar-icon.png"
  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  rss = true
  comments = false
  readingTime = true
  modifyLink = true
  GithubEdit = "https://github.com/RMHogervorst/blog/tree/master/content/"
  useHLJS = true
  selfHosted = false

[Author]
  name = "Roel M. Hogervorst"
  website = "rmhogervorst.nl"
  email = "hogervorst.rm@gmail.com"
  keybase = "rmhogervorst"
  github = "RMHogervorst"
  gitlab = "rmhogervorst"
  bitbucket = "RMHogervorst"
  twitter = "RoelMHogervorst"
  linkedin = "rmhogervorst"
  stackoverflow = "users/5573955/roel-hogervorst"
  devto = "rmhogervorst"
  mastodon = "mastodon.technology/@rmhogervorst"
 
[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

[[menu.main]]
    name = "About"
    url = "about/"
    weight = 3
    
[[menu.main]]
    name = "Getting updates"
    url = "subscribing"
    weight = 3

[[menu.main]]
    name = "search and more "
    url = "search_and_more/"
    weight = 3
