theme = "beautifulhugo"
baseURL = "https://blog.rmhogervorst.nl"
languageCode = "en-us"
DefaultContentLanguage = "en"
title = "Roel's R-tefacts"
pygmentsCodeFences = true
pygmentsUseClasses = false
pygmentsStyle = "trac"
pygmentsUseClassic = true
enableEmoji = true
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "index\\.html",  "\\.knit\\.md$", "\\.utf8\\.md$"]
publishDir = "public"
ignoreErrors = ["error-remote-getjson"]

[markup.goldmark.renderer]
unsafe= true

[permalinks]
    post = "/blog/:year/:month/:day/:slug/"

[Params]
  subtitle = "Tips about clean R-code and reproducible work, but also fun!"
  logo = "img/avatar-icon.png"
  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  rss = true
  comments = false
  readingTime = true
  modifyLink = true
  GithubEdit = "https://github.com/RMHogervorst/blog/tree/master/content/"
  useHLJS = true
  selfHosted = false
  wordCount = true
  showRelatedPosts = true

[taxonomies]
   category = 'categories'
   tag = 'tags'
   post-type = 'post-type'
   difficulty = 'difficulty'

[Author]
  name = "Roel M. Hogervorst"
  website = "rmhogervorst.nl"
  email = "hogervorst.rm+blog@gmail.com"
  github = "RMHogervorst"
  gitlab = "rmhogervorst"
  bitbucket = "RMHogervorst"
  linkedin = "rmhogervorst"
  devto = "rmhogervorst"
  mastodon = "mastodon.world/@rmhogervorst"
  orchid = "0000-0001-7509-0328"
  r-universe = "rmhogervorst"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "About"
    url = "about/"
    weight = 2

[[menu.main]]
    name = "Getting updates"
    url = "subscribing"
    weight = 3

[[menu.main]]
    name = "search and more "
    url = "search_and_more/"
    weight = 4

[outputs]
   home = [ "HTML", "JSON" ]
