theme = "beautifulhugo"
baseURL = "https://blog.rmhogervorst.nl/"
languageCode = "en-us"
title = "Roel's R-tefacts"
pygmentsCodeFences = true
pygmentsUseClasses = true
enableEmoji = true
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
publishDir = "public"

[permalinks]
    post = "/blog/:year/:month/:day/:slug/"
    
[Params]
  subtitle = "Tips about clean R-code and reproducible work, but also fun!"
  logo = "img/avatar-icon.png"
  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  rss = true
  comments = true
  readingTime = true
  modifyLink = true
  GithubEdit = "https://github.com/RMHogervorst/blog/tree/master/content/"


[Author]
  name = "Roel M. Hogervorst"
  website = "rmhogervorst.nl"
  email = "hogervorst.rm@gmail.com"
  keybase = "rmhogervorst"
  github = "RMHogervorst"
  gitlab = "rmhogervorst"
  bitbucket = "RMHogervorst"
  twitter = "RoelMHogervorst"
  linkedin = "rmhogervorst"
  stackoverflow = "users/5573955/roel-hogervorst"
 
[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

[[menu.main]]
    name = "About"
    url = "about/"
    weight = 3
    
[[menu.main]]
    name = "Getting updates"
    url = "subscribing"
    weight = 3

[[menu.main.more]]
    name = "all tags"
    url = "tags/"
    weight = 4

[[menu.main.more]]
    name = "all categories"
    url = "categories/"
    weight = 4

[[menu.main.more]]
    name = "half ideas"
    url = "https://notes.rmhogervorst.nl/"
    weight = 4
