# Global settings applied to the whole site.
[build]
  command = "hugo"
  publish = "public"


[context.production.environment]
  HUGO_VERSION = "0.60.0"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[context.branch-deploy.environment]
  HUGO_VERSION = "0.60.0"

[context.deploy-preview]
command = "hugo -b $DEPLOY_PRIME_URL --buildFuture"

[context.branch-deploy]
command = "hugo -b $DEPLOY_PRIME_URL --buildFuture"
